### ISSUE TITLE
Do we need the <base> tag?

### ISSUE THREAD

**Issue by montalvomiguelo** [slavafyi/vite-plugin-shopify-import-maps#1]
Hi @slavamak (: 

Do we need the `<base>` tag? _I removed it from [my demo](https://shop.montalvomiguelo.com/collections/all?preview_theme_id=132745035947), and it's working fine_.

https://github.com/slavamak/vite-plugin-shopify-import-maps/blob/28bc1fc39897bf24f5911d1fb1c12440c1bdf656/src/import-maps.ts#L44

**Comment by slavafyi** [comment]
@montalvomiguelo Hi Miguel! Actually, yes, it is important. Because without the <base> tag, module resolution doesn't work properly if we want to use the hash ?v= . In your demo, it works because import-maps is not used. You can delete the `importmap.liquid` from theme and nothing will change. Because I see option `versionNumbers` is false.

Btw thank you for add option https://github.com/barrel/shopify-vite/pull/99 for vite plugin!

**Comment by montalvomiguelo** [comment]
Oops, I just enabled the version numbers. 
Module resolution is working nicely in my demo with the help of the `<base>` tag. 

Thanks a lot for this Plugin @slavamak 🙏
